### ISSUE TITLE
Define Pilot Use-Cases

### ISSUE THREAD

**Issue by Flaxscrip** [cryptotechguru/EDENomicon#23]
We need to define a set of use-cases for the summer 2020 pilots!

**Comment by Flaxscrip** [comment]
Please review [EDEN-Pilot-Example](https://nomicon.edenprotocol.io/Projects/2020-Pilot-Project/EDEN-Pilot-Example.html)

This describes a generic set of pilot activities including a farm, lab, end-user, and analytics company.

**Comment by angelabacca** [comment]
There are five sets of data collection I think would be a good start for a pilot on the timetable we are working with: genotype data, phenotype data, environmental data, chemotype data and quality scoring. This is the first step to having a better understanding of cannabis varieties (cultivars). 

1. GENOTYPE DATA: This is the underlying piece of data that ties all the rest together. If breeders/growers have sequenced their varieties with Phylos we should find a way we can allow them to share (Daniel or Eviane will know more about whether or not there is a data file available to the growers they can upload). As you already know, Kannapedia is already doing the exact same thing here. There are a handful of other sequencing companies, but those are the big two. All the growers/breeders in the pilot will have sequenced their varieties so that we can demonstrate how genetics as a baseline ties all this data together. (Beyond the genetic sequencing itself, people may also want to indicate plant lineage.). 

2. PHENOTYPE DATA: Data about what the plant physically looks like throughout stages of growth. This will likely be self reported (growth during vegetative stage, growth during flowering, final height), size and shape of the leaves, branching traits, colors, etc. 

3. ENVIRONMENTAL DATA: This would either be self reported, or reported through automatic sensors and controllers. This is all the data detailing the plants environment as it moved through the growth stages to harvest. If you would like a list of companies I can provide one -- there are a ton of automatic indoor agricultural products that are in mass use and track data about the plant's growing environment: light intensity and spectrum, water quality and quantity, temperature, humidity, air quality, grow media, nutrients and etc. 

4. CHEMOTYPE DATA: Data provided will likely come from state-mandated lab testing. Either data can come from a lab or METRC (METRC is the state-mandated seed-to-sale software in use in the majority of the market. There are others, and various other software programs that interact with it for the clients because its not user friendly. Testing will still come from a lab, but is reported in METRC and so available there if not the lab). At the bare minimum all jurisdictions are requiring cannabinoid testing, pesticide testing and mold testing. Growers/Breeders can pay extra for terpene testing and those in our pilot likely are/will (terpenes -- the essential oils in the plant that give them their unique smells. In very rare instances other plant compounds are now being tracked, such as flavonoids. As this expands to other plant life, other chemical profiles of other plant compounds will become more relevant as well. 

5. QUALITY DATA: Third-party quality scoring. Jhavid's company operates on the West Coast and uses a standard to provide a digital certificate of quality scoring. His non-profit has a standard they maintain designed from USDA ag standards. He is participating in the pilot and growers/breeders can collect this data too. https://ichstandards.org/

If people bring a lot of back data to the pilot, we may be able to extrapolate interesting trends but also create a lot of value in the network right away. This is the type of data collection that is needed to be able to start understanding plant cultivars - the first step to being able to start identifying predictability in user effects.  I would want the doctors and lawyers in the pilot to be able to look at HOW they and other stakeholders can integrate what they do and how they do it into the network. We don't have all the best data to get real answers from, yet, but by starting at the baseline of the plant itself-- its nature and nurture -- we can start the next steps to better answers where they are needed. For the pilot I would want these other stakeholders to be able to show a short-term roadmap to bringing themselves and other stakeholders who will find value in the network.

**Comment by Flaxscrip** [comment]
@angelabacca - This will be very useful structure once we develop the protocol further. For now, we need to stay focused on what is achievable within the next 2-3 months. That limits, at least for the purpose and duration of the pilots, our data capture to simple points. The [EDEN Pilot Example](https://nomicon.edenprotocol.io/Projects/2020-Pilot-Project/EDEN-Pilot-Example.html) is certainly close to the limit of what we'll be able to do technically in this short period.

Your requirements above remain valid for what I've been describing as "Step 2", which will involve cataloging the information for publication and consumption. That's not far behind "Step 1", which is simply to notarize IP and claims along the supply chain.

**Comment by Flaxscrip** [comment]
I'll work on translating the marketing slides we've bee using into a more defined timeline or roadmap within EDENomicon. That will allow us to target important requirements, like your post above, to the appropriate phase of the project.

**Comment by angelabacca** [comment]
The Eden Pilot example looks pretty close to what I am saying. I am not sure what you are looking for me here than, perhaps I misunderstood the original question you were asking of me?

**Comment by Flaxscrip** [comment]
Let's sync-up today on a call today. We'll go through the nomicon and how you can help.

**Comment by Flaxscrip** [comment]
Issue #26 should help us create a roadmap to capture future requirements like @angelabacca's comments above.

**Comment by Flaxscrip** [comment]
Closing this issue. We will re-define the Pilot Use Cases as part of Project Metatron.
